<?php
/**
 * V11VmOpenApiServiceChannelServiceInBase
 *
 * PHP version 5
 *
 * @category Class
 * @package  Tampere\PtvV11
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PTV Open Api version 11
 *
 * Here you can see listed all the PTV Open Api methods.
 *
 * OpenAPI spec version: v11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.29
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Tampere\PtvV11\PtvModel;

use \ArrayAccess;
use \Tampere\PtvV11\ObjectSerializer;

/**
 * V11VmOpenApiServiceChannelServiceInBase Class Doc Comment
 *
 * @category Class
 * @description OPEN API V11 - View Model of service channel service  IN.
 * @package  Tampere\PtvV11
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class V11VmOpenApiServiceChannelServiceInBase implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'V11VmOpenApiServiceChannelServiceInBase';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'serviceId' => 'string',
'serviceChargeType' => 'string',
'description' => '\Tampere\PtvV11\PtvModel\VmOpenApiLocalizedListItem[]',
'extraTypes' => '\Tampere\PtvV11\PtvModel\VmOpenApiExtraType[]',
'serviceHours' => '\Tampere\PtvV11\PtvModel\V11VmOpenApiServiceHour[]',
'contactDetails' => '\Tampere\PtvV11\PtvModel\V9VmOpenApiContactDetailsInBase',
'deleteServiceChargeType' => 'bool',
'deleteAllDescriptions' => 'bool',
'deleteAllExtraTypes' => 'bool',
'deleteAllServiceHours' => 'bool',
'serviceGuid' => 'string',
'channelGuid' => 'string',
'isASTIConnection' => 'bool'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'serviceId' => null,
'serviceChargeType' => null,
'description' => null,
'extraTypes' => null,
'serviceHours' => null,
'contactDetails' => null,
'deleteServiceChargeType' => null,
'deleteAllDescriptions' => null,
'deleteAllExtraTypes' => null,
'deleteAllServiceHours' => null,
'serviceGuid' => 'uuid',
'channelGuid' => 'uuid',
'isASTIConnection' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'serviceId' => 'serviceId',
'serviceChargeType' => 'serviceChargeType',
'description' => 'description',
'extraTypes' => 'extraTypes',
'serviceHours' => 'serviceHours',
'contactDetails' => 'contactDetails',
'deleteServiceChargeType' => 'deleteServiceChargeType',
'deleteAllDescriptions' => 'deleteAllDescriptions',
'deleteAllExtraTypes' => 'deleteAllExtraTypes',
'deleteAllServiceHours' => 'deleteAllServiceHours',
'serviceGuid' => 'serviceGuid',
'channelGuid' => 'channelGuid',
'isASTIConnection' => 'isASTIConnection'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'serviceId' => 'setServiceId',
'serviceChargeType' => 'setServiceChargeType',
'description' => 'setDescription',
'extraTypes' => 'setExtraTypes',
'serviceHours' => 'setServiceHours',
'contactDetails' => 'setContactDetails',
'deleteServiceChargeType' => 'setDeleteServiceChargeType',
'deleteAllDescriptions' => 'setDeleteAllDescriptions',
'deleteAllExtraTypes' => 'setDeleteAllExtraTypes',
'deleteAllServiceHours' => 'setDeleteAllServiceHours',
'serviceGuid' => 'setServiceGuid',
'channelGuid' => 'setChannelGuid',
'isASTIConnection' => 'setIsASTIConnection'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'serviceId' => 'getServiceId',
'serviceChargeType' => 'getServiceChargeType',
'description' => 'getDescription',
'extraTypes' => 'getExtraTypes',
'serviceHours' => 'getServiceHours',
'contactDetails' => 'getContactDetails',
'deleteServiceChargeType' => 'getDeleteServiceChargeType',
'deleteAllDescriptions' => 'getDeleteAllDescriptions',
'deleteAllExtraTypes' => 'getDeleteAllExtraTypes',
'deleteAllServiceHours' => 'getDeleteAllServiceHours',
'serviceGuid' => 'getServiceGuid',
'channelGuid' => 'getChannelGuid',
'isASTIConnection' => 'getIsASTIConnection'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['serviceId'] = isset($data['serviceId']) ? $data['serviceId'] : null;
        $this->container['serviceChargeType'] = isset($data['serviceChargeType']) ? $data['serviceChargeType'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['extraTypes'] = isset($data['extraTypes']) ? $data['extraTypes'] : null;
        $this->container['serviceHours'] = isset($data['serviceHours']) ? $data['serviceHours'] : null;
        $this->container['contactDetails'] = isset($data['contactDetails']) ? $data['contactDetails'] : null;
        $this->container['deleteServiceChargeType'] = isset($data['deleteServiceChargeType']) ? $data['deleteServiceChargeType'] : null;
        $this->container['deleteAllDescriptions'] = isset($data['deleteAllDescriptions']) ? $data['deleteAllDescriptions'] : null;
        $this->container['deleteAllExtraTypes'] = isset($data['deleteAllExtraTypes']) ? $data['deleteAllExtraTypes'] : null;
        $this->container['deleteAllServiceHours'] = isset($data['deleteAllServiceHours']) ? $data['deleteAllServiceHours'] : null;
        $this->container['serviceGuid'] = isset($data['serviceGuid']) ? $data['serviceGuid'] : null;
        $this->container['channelGuid'] = isset($data['channelGuid']) ? $data['channelGuid'] : null;
        $this->container['isASTIConnection'] = isset($data['isASTIConnection']) ? $data['isASTIConnection'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['serviceId'] === null) {
            $invalidProperties[] = "'serviceId' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets serviceId
     *
     * @return string
     */
    public function getServiceId()
    {
        return $this->container['serviceId'];
    }

    /**
     * Sets serviceId
     *
     * @param string $serviceId PTV service identifier.
     *
     * @return $this
     */
    public function setServiceId($serviceId)
    {
        $this->container['serviceId'] = $serviceId;

        return $this;
    }

    /**
     * Gets serviceChargeType
     *
     * @return string
     */
    public function getServiceChargeType()
    {
        return $this->container['serviceChargeType'];
    }

    /**
     * Sets serviceChargeType
     *
     * @param string $serviceChargeType Service charge type. Possible values are: Chargeable, FreeOfCharge or Other.
     *
     * @return $this
     */
    public function setServiceChargeType($serviceChargeType)
    {
        $this->container['serviceChargeType'] = $serviceChargeType;

        return $this;
    }

    /**
     * Gets description
     *
     * @return \Tampere\PtvV11\PtvModel\VmOpenApiLocalizedListItem[]
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param \Tampere\PtvV11\PtvModel\VmOpenApiLocalizedListItem[] $description List of localized service channel relationship descriptions. Possible type values are: Description, ChargeTypeAdditionalInfo. (Max.Length: 500 Description). (Max.Length: 500 ChargeTypeAdditionalInfo).
     *
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets extraTypes
     *
     * @return \Tampere\PtvV11\PtvModel\VmOpenApiExtraType[]
     */
    public function getExtraTypes()
    {
        return $this->container['extraTypes'];
    }

    /**
     * Sets extraTypes
     *
     * @param \Tampere\PtvV11\PtvModel\VmOpenApiExtraType[] $extraTypes The extra types related to service and service channel connection.
     *
     * @return $this
     */
    public function setExtraTypes($extraTypes)
    {
        $this->container['extraTypes'] = $extraTypes;

        return $this;
    }

    /**
     * Gets serviceHours
     *
     * @return \Tampere\PtvV11\PtvModel\V11VmOpenApiServiceHour[]
     */
    public function getServiceHours()
    {
        return $this->container['serviceHours'];
    }

    /**
     * Sets serviceHours
     *
     * @param \Tampere\PtvV11\PtvModel\V11VmOpenApiServiceHour[] $serviceHours List of connection related service hours.
     *
     * @return $this
     */
    public function setServiceHours($serviceHours)
    {
        $this->container['serviceHours'] = $serviceHours;

        return $this;
    }

    /**
     * Gets contactDetails
     *
     * @return \Tampere\PtvV11\PtvModel\V9VmOpenApiContactDetailsInBase
     */
    public function getContactDetails()
    {
        return $this->container['contactDetails'];
    }

    /**
     * Sets contactDetails
     *
     * @param \Tampere\PtvV11\PtvModel\V9VmOpenApiContactDetailsInBase $contactDetails contactDetails
     *
     * @return $this
     */
    public function setContactDetails($contactDetails)
    {
        $this->container['contactDetails'] = $contactDetails;

        return $this;
    }

    /**
     * Gets deleteServiceChargeType
     *
     * @return bool
     */
    public function getDeleteServiceChargeType()
    {
        return $this->container['deleteServiceChargeType'];
    }

    /**
     * Sets deleteServiceChargeType
     *
     * @param bool $deleteServiceChargeType Indicates if value for property ServiceChargeType should be deleted.
     *
     * @return $this
     */
    public function setDeleteServiceChargeType($deleteServiceChargeType)
    {
        $this->container['deleteServiceChargeType'] = $deleteServiceChargeType;

        return $this;
    }

    /**
     * Gets deleteAllDescriptions
     *
     * @return bool
     */
    public function getDeleteAllDescriptions()
    {
        return $this->container['deleteAllDescriptions'];
    }

    /**
     * Sets deleteAllDescriptions
     *
     * @param bool $deleteAllDescriptions Indicates if all descriptions should be deleted.
     *
     * @return $this
     */
    public function setDeleteAllDescriptions($deleteAllDescriptions)
    {
        $this->container['deleteAllDescriptions'] = $deleteAllDescriptions;

        return $this;
    }

    /**
     * Gets deleteAllExtraTypes
     *
     * @return bool
     */
    public function getDeleteAllExtraTypes()
    {
        return $this->container['deleteAllExtraTypes'];
    }

    /**
     * Sets deleteAllExtraTypes
     *
     * @param bool $deleteAllExtraTypes Indicates if all extra types should be deleted.
     *
     * @return $this
     */
    public function setDeleteAllExtraTypes($deleteAllExtraTypes)
    {
        $this->container['deleteAllExtraTypes'] = $deleteAllExtraTypes;

        return $this;
    }

    /**
     * Gets deleteAllServiceHours
     *
     * @return bool
     */
    public function getDeleteAllServiceHours()
    {
        return $this->container['deleteAllServiceHours'];
    }

    /**
     * Sets deleteAllServiceHours
     *
     * @param bool $deleteAllServiceHours Gets or sets a value indicating whether all service hours should be delted.
     *
     * @return $this
     */
    public function setDeleteAllServiceHours($deleteAllServiceHours)
    {
        $this->container['deleteAllServiceHours'] = $deleteAllServiceHours;

        return $this;
    }

    /**
     * Gets serviceGuid
     *
     * @return string
     */
    public function getServiceGuid()
    {
        return $this->container['serviceGuid'];
    }

    /**
     * Sets serviceGuid
     *
     * @param string $serviceGuid Gets or sets the service unique identifier.
     *
     * @return $this
     */
    public function setServiceGuid($serviceGuid)
    {
        $this->container['serviceGuid'] = $serviceGuid;

        return $this;
    }

    /**
     * Gets channelGuid
     *
     * @return string
     */
    public function getChannelGuid()
    {
        return $this->container['channelGuid'];
    }

    /**
     * Sets channelGuid
     *
     * @param string $channelGuid Gets or sets the channel unique identifier.
     *
     * @return $this
     */
    public function setChannelGuid($channelGuid)
    {
        $this->container['channelGuid'] = $channelGuid;

        return $this;
    }

    /**
     * Gets isASTIConnection
     *
     * @return bool
     */
    public function getIsASTIConnection()
    {
        return $this->container['isASTIConnection'];
    }

    /**
     * Sets isASTIConnection
     *
     * @param bool $isASTIConnection Indicates if connection between service and service channel is ASTI related.
     *
     * @return $this
     */
    public function setIsASTIConnection($isASTIConnection)
    {
        $this->container['isASTIConnection'] = $isASTIConnection;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
