<?php
/**
 * V10VmOpenApiOrganizationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Tampere\PtvV11
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PTV Open Api version 11
 *
 * Here you can see listed all the PTV Open Api methods.
 *
 * OpenAPI spec version: v11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.29
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Tampere\PtvV11;

/**
 * V10VmOpenApiOrganizationTest Class Doc Comment
 *
 * @category    Class
 * @description OPEN API V10 - View Model of organization
 * @package     Tampere\PtvV11
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V10VmOpenApiOrganizationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "V10VmOpenApiOrganization"
     */
    public function testV10VmOpenApiOrganization()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "oid"
     */
    public function testPropertyOid()
    {
    }

    /**
     * Test attribute "sourceId"
     */
    public function testPropertySourceId()
    {
    }

    /**
     * Test attribute "organizationType"
     */
    public function testPropertyOrganizationType()
    {
    }

    /**
     * Test attribute "businessCode"
     */
    public function testPropertyBusinessCode()
    {
    }

    /**
     * Test attribute "businessName"
     */
    public function testPropertyBusinessName()
    {
    }

    /**
     * Test attribute "organizationNames"
     */
    public function testPropertyOrganizationNames()
    {
    }

    /**
     * Test attribute "displayNameType"
     */
    public function testPropertyDisplayNameType()
    {
    }

    /**
     * Test attribute "areaType"
     */
    public function testPropertyAreaType()
    {
    }

    /**
     * Test attribute "organizationDescriptions"
     */
    public function testPropertyOrganizationDescriptions()
    {
    }

    /**
     * Test attribute "emails"
     */
    public function testPropertyEmails()
    {
    }

    /**
     * Test attribute "phoneNumbers"
     */
    public function testPropertyPhoneNumbers()
    {
    }

    /**
     * Test attribute "webPages"
     */
    public function testPropertyWebPages()
    {
    }

    /**
     * Test attribute "electronicInvoicings"
     */
    public function testPropertyElectronicInvoicings()
    {
    }

    /**
     * Test attribute "businessId"
     */
    public function testPropertyBusinessId()
    {
    }

    /**
     * Test attribute "versionId"
     */
    public function testPropertyVersionId()
    {
    }

    /**
     * Test attribute "parentOrganizationId"
     */
    public function testPropertyParentOrganizationId()
    {
    }

    /**
     * Test attribute "organizationRootId"
     */
    public function testPropertyOrganizationRootId()
    {
    }

    /**
     * Test attribute "municipality"
     */
    public function testPropertyMunicipality()
    {
    }

    /**
     * Test attribute "areas"
     */
    public function testPropertyAreas()
    {
    }

    /**
     * Test attribute "areaMunicipalities"
     */
    public function testPropertyAreaMunicipalities()
    {
    }

    /**
     * Test attribute "addresses"
     */
    public function testPropertyAddresses()
    {
    }

    /**
     * Test attribute "publishingStatus"
     */
    public function testPropertyPublishingStatus()
    {
    }

    /**
     * Test attribute "services"
     */
    public function testPropertyServices()
    {
    }

    /**
     * Test attribute "responsibleOrganizationServices"
     */
    public function testPropertyResponsibleOrganizationServices()
    {
    }

    /**
     * Test attribute "producerOrganizationServices"
     */
    public function testPropertyProducerOrganizationServices()
    {
    }

    /**
     * Test attribute "modified"
     */
    public function testPropertyModified()
    {
    }

    /**
     * Test attribute "subOrganizations"
     */
    public function testPropertySubOrganizations()
    {
    }

    /**
     * Test attribute "availableLanguages"
     */
    public function testPropertyAvailableLanguages()
    {
    }
}
