<?php
/**
 * V11VmOpenApiServiceChannelServiceTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Tampere\PtvV11
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PTV Open Api version 11
 *
 * Here you can see listed all the PTV Open Api methods.
 *
 * The version of the OpenAPI document: v11
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Tampere\PtvV11\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * V11VmOpenApiServiceChannelServiceTest Class Doc Comment
 *
 * @category    Class
 * @description OPEN API - View Model of Service channel service V10
 * @package     Tampere\PtvV11
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class V11VmOpenApiServiceChannelServiceTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "V11VmOpenApiServiceChannelService"
     */
    public function testV11VmOpenApiServiceChannelService()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "serviceChargeType"
     */
    public function testPropertyServiceChargeType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "serviceHours"
     */
    public function testPropertyServiceHours()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "isASTIConnection"
     */
    public function testPropertyIsASTIConnection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ownerReferenceId"
     */
    public function testPropertyOwnerReferenceId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "service"
     */
    public function testPropertyService()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "extraTypes"
     */
    public function testPropertyExtraTypes()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "contactDetails"
     */
    public function testPropertyContactDetails()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "digitalAuthorizations"
     */
    public function testPropertyDigitalAuthorizations()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "modified"
     */
    public function testPropertyModified()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
