<?php
/**
 * V4VmOpenApiEmailTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Tampere\PtvV11
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PTV Open Api version 11
 *
 * Here you can see listed all the PTV Open Api methods.
 *
 * OpenAPI spec version: v11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.29
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Tampere\PtvV11;

/**
 * V4VmOpenApiEmailTest Class Doc Comment
 *
 * @category    Class
 * @description OPEN API V4 - View Model of email
 * @package     Tampere\PtvV11
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V4VmOpenApiEmailTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "V4VmOpenApiEmail"
     */
    public function testV4VmOpenApiEmail()
    {
    }

    /**
     * Test attribute "language"
     */
    public function testPropertyLanguage()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "ownerReferenceId"
     */
    public function testPropertyOwnerReferenceId()
    {
    }

    /**
     * Test attribute "ownerReferenceId2"
     */
    public function testPropertyOwnerReferenceId2()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "value"
     */
    public function testPropertyValue()
    {
    }

    /**
     * Test attribute "existsOnePerLanguage"
     */
    public function testPropertyExistsOnePerLanguage()
    {
    }

    /**
     * Test attribute "orderNumber"
     */
    public function testPropertyOrderNumber()
    {
    }
}
