<?php
/**
 * V4VmOpenApiFintoItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Tampere\PtvV11
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PTV Open Api version 11
 *
 * Here you can see listed all the PTV Open Api methods.
 *
 * OpenAPI spec version: v11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.29
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Tampere\PtvV11;

/**
 * V4VmOpenApiFintoItemTest Class Doc Comment
 *
 * @category    Class
 * @description OPEN API V4 - View Model of finto item
 * @package     Tampere\PtvV11
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V4VmOpenApiFintoItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "V4VmOpenApiFintoItem"
     */
    public function testV4VmOpenApiFintoItem()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
    }

    /**
     * Test attribute "ontologyType"
     */
    public function testPropertyOntologyType()
    {
    }

    /**
     * Test attribute "uri"
     */
    public function testPropertyUri()
    {
    }

    /**
     * Test attribute "parentId"
     */
    public function testPropertyParentId()
    {
    }

    /**
     * Test attribute "parentUri"
     */
    public function testPropertyParentUri()
    {
    }

    /**
     * Test attribute "override"
     */
    public function testPropertyOverride()
    {
    }

    /**
     * Test attribute "newUri"
     */
    public function testPropertyNewUri()
    {
    }

    /**
     * Test attribute "newParentUri"
     */
    public function testPropertyNewParentUri()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }
}
