<?php
/**
 * V8VmOpenApiAddressDeliveryInTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Tampere\PtvV11
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PTV Open Api version 11
 *
 * Here you can see listed all the PTV Open Api methods.
 *
 * OpenAPI spec version: v11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.29
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Tampere\PtvV11;

/**
 * V8VmOpenApiAddressDeliveryInTest Class Doc Comment
 *
 * @category    Class
 * @description OPEN API V8 - View Model of delivery address
 * @package     Tampere\PtvV11
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V8VmOpenApiAddressDeliveryInTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "V8VmOpenApiAddressDeliveryIn"
     */
    public function testV8VmOpenApiAddressDeliveryIn()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "subType"
     */
    public function testPropertySubType()
    {
    }

    /**
     * Test attribute "postOfficeBoxAddress"
     */
    public function testPropertyPostOfficeBoxAddress()
    {
    }

    /**
     * Test attribute "streetAddress"
     */
    public function testPropertyStreetAddress()
    {
    }

    /**
     * Test attribute "deliveryAddressInText"
     */
    public function testPropertyDeliveryAddressInText()
    {
    }

    /**
     * Test attribute "formReceiver"
     */
    public function testPropertyFormReceiver()
    {
    }

    /**
     * Test attribute "orderNumber"
     */
    public function testPropertyOrderNumber()
    {
    }
}
