<?php
/**
 * V9VmOpenApiEntranceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Tampere\PtvV11
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PTV Open Api version 11
 *
 * Here you can see listed all the PTV Open Api methods.
 *
 * OpenAPI spec version: v11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.29
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Tampere\PtvV11;

/**
 * V9VmOpenApiEntranceTest Class Doc Comment
 *
 * @category    Class
 * @description OPEN API - View Model of entrance for address
 * @package     Tampere\PtvV11
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V9VmOpenApiEntranceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "V9VmOpenApiEntrance"
     */
    public function testV9VmOpenApiEntrance()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "isMainEntrance"
     */
    public function testPropertyIsMainEntrance()
    {
    }

    /**
     * Test attribute "coordinates"
     */
    public function testPropertyCoordinates()
    {
    }

    /**
     * Test attribute "accessibilitySentences"
     */
    public function testPropertyAccessibilitySentences()
    {
    }

    /**
     * Test attribute "contactInfo"
     */
    public function testPropertyContactInfo()
    {
    }
}
