<?php
/**
 * VmOpenApiArchivedServiceChannelBaseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Tampere\PtvV11
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PTV Open Api version 11
 *
 * Here you can see listed all the PTV Open Api methods.
 *
 * OpenAPI spec version: v11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.29
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Tampere\PtvV11;

/**
 * VmOpenApiArchivedServiceChannelBaseTest Class Doc Comment
 *
 * @category    Class
 * @description Model
 * @package     Tampere\PtvV11
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VmOpenApiArchivedServiceChannelBaseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "VmOpenApiArchivedServiceChannelBase"
     */
    public function testVmOpenApiArchivedServiceChannelBase()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "organizationId"
     */
    public function testPropertyOrganizationId()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "archivingDate"
     */
    public function testPropertyArchivingDate()
    {
    }

    /**
     * Test attribute "names"
     */
    public function testPropertyNames()
    {
    }
}
