<?php
/**
 * VmOpenApiAddressStreetWithCoordinatesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Tampere\PtvV11
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PTV Open Api version 11
 *
 * Here you can see listed all the PTV Open Api methods.
 *
 * OpenAPI spec version: v11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.29
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Tampere\PtvV11;

/**
 * VmOpenApiAddressStreetWithCoordinatesTest Class Doc Comment
 *
 * @category    Class
 * @description OPEN API V7 - View Model of address with type
 * @package     Tampere\PtvV11
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VmOpenApiAddressStreetWithCoordinatesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "VmOpenApiAddressStreetWithCoordinates"
     */
    public function testVmOpenApiAddressStreetWithCoordinates()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "postalCode"
     */
    public function testPropertyPostalCode()
    {
    }

    /**
     * Test attribute "postOffice"
     */
    public function testPropertyPostOffice()
    {
    }

    /**
     * Test attribute "municipality"
     */
    public function testPropertyMunicipality()
    {
    }

    /**
     * Test attribute "additionalInformation"
     */
    public function testPropertyAdditionalInformation()
    {
    }

    /**
     * Test attribute "street"
     */
    public function testPropertyStreet()
    {
    }

    /**
     * Test attribute "streetNumber"
     */
    public function testPropertyStreetNumber()
    {
    }

    /**
     * Test attribute "latitude"
     */
    public function testPropertyLatitude()
    {
    }

    /**
     * Test attribute "longitude"
     */
    public function testPropertyLongitude()
    {
    }

    /**
     * Test attribute "coordinateState"
     */
    public function testPropertyCoordinateState()
    {
    }
}
