<?php
/**
 * CodeListApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Tampere\PtvV11
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PTV Open Api version 11
 *
 * Here you can see listed all the PTV Open Api methods.
 *
 * The version of the OpenAPI document: v11
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Tampere\PtvV11\Test\Api;

use \Tampere\PtvV11\Configuration;
use \Tampere\PtvV11\ApiException;
use \Tampere\PtvV11\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CodeListApiTest Class Doc Comment
 *
 * @category Class
 * @package  Tampere\PtvV11
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CodeListApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiV11CodeListGetAreaCodesTypeTypeGet
     *
     * Gets a list of area codes filtered by area type..
     *
     */
    public function testApiV11CodeListGetAreaCodesTypeTypeGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV11CodeListGetCountryCodesGet
     *
     * Gets a list of country codes..
     *
     */
    public function testApiV11CodeListGetCountryCodesGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV11CodeListGetLanguageCodesGet
     *
     * Gets a list of language codes..
     *
     */
    public function testApiV11CodeListGetLanguageCodesGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV11CodeListGetMunicipalityCodesGet
     *
     * Gets a list of municipality codes..
     *
     */
    public function testApiV11CodeListGetMunicipalityCodesGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV11CodeListGetPostalCodesGet
     *
     * Gets a list of postal codes..
     *
     */
    public function testApiV11CodeListGetPostalCodesGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
