<?php
/**
 * ConnectionApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Tampere\PtvV11
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PTV Open Api version 11
 *
 * Here you can see listed all the PTV Open Api methods.
 *
 * The version of the OpenAPI document: v11
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Tampere\PtvV11\Test\Api;

use \Tampere\PtvV11\Configuration;
use \Tampere\PtvV11\ApiException;
use \Tampere\PtvV11\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ConnectionApiTest Class Doc Comment
 *
 * @category Class
 * @package  Tampere\PtvV11
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ConnectionApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiV11ConnectionASTIServiceChannelIdServiceChannelIdPut
     *
     * Updates connections between a service channel and services with extra data.  Request includes services for one certain service channel and missing ASTI connections are removed. Regular connections are left as they are.  To delete all ASTI connections for a service channel set 'deleteAllServiceRelations' property to true.  This is special endpoint for ASTI and users need to have special access right to be able use it..
     *
     */
    public function testApiV11ConnectionASTIServiceChannelIdServiceChannelIdPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV11ConnectionASTIServiceIdServiceIdPut
     *
     * Updates connections between a service and service channels with extra data.  Request includes service channels for one certain service and missing ASTI connections are removed. Regular connections are left as they are.  To delete all ASTI service channel connections for a service, set 'deleteAllChannelRelations' property to true.  This is special endpoint for ASTI and users need to have special access right to be able use it..
     *
     */
    public function testApiV11ConnectionASTIServiceIdServiceIdPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV11ConnectionASTIServiceSourceIdServiceSourceIdPut
     *
     * Updates connections between a service and service channels with extra data. External source ids are used.  Request includes service channels for one certain service and missing ASTI connections are removed. Regular connections are left as they are.  To delete all ASTI service channel connections for a service set 'deleteAllChannelRelations' property to true.  This is special endpoint for ASTI and users need to have special access right to be able use it..
     *
     */
    public function testApiV11ConnectionASTIServiceSourceIdServiceSourceIdPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV11ConnectionPost
     *
     * Creates a connections between services and service channels with extra data..
     *
     */
    public function testApiV11ConnectionPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV11ConnectionServiceIdServiceIdPut
     *
     * Updates connections between a service and service channels with extra data.  Request includes service channels for one certain service so regular connections missing from request are removed.  ASTI connections are left as they are.  To delete all regular service channel connections for a service, set 'deleteAllChannelRelations' property to true..
     *
     */
    public function testApiV11ConnectionServiceIdServiceIdPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV11ConnectionServiceSourceIdServiceSourceIdPut
     *
     * Updates connections between a service and service channels with extra data. External source ids are used.  Request includes service channels for one certain service so service channels missing from request are removed.  To delete all service channel connections for a service set 'deleteAllChannelRelations' property to true.  ASTI connections are not removed - data for those connections can be updated though..
     *
     */
    public function testApiV11ConnectionServiceSourceIdServiceSourceIdPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV11ConnectionSourcePost
     *
     * Creates a connections between services and service channels with extra data. External source ids are used..
     *
     */
    public function testApiV11ConnectionSourcePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
