<?php
/**
 * GeneralDescriptionApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Tampere\PtvV11
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PTV Open Api version 11
 *
 * Here you can see listed all the PTV Open Api methods.
 *
 * The version of the OpenAPI document: v11
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Tampere\PtvV11\Test\Api;

use \Tampere\PtvV11\Configuration;
use \Tampere\PtvV11\ApiException;
use \Tampere\PtvV11\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * GeneralDescriptionApiTest Class Doc Comment
 *
 * @category Class
 * @package  Tampere\PtvV11
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class GeneralDescriptionApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiV11GeneralDescriptionGet
     *
     * Gets all the statutory service general descriptions within PTV as a list of ids and names.  General descriptions created/modified after certain date can be fetched by adding date as query string parameter.  General descriptions created/modified before certain date can be fetched by adding dateBefore as query string parameter..
     *
     */
    public function testApiV11GeneralDescriptionGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV11GeneralDescriptionIdGet
     *
     * Fetches all the information related to a single statutory service general description..
     *
     */
    public function testApiV11GeneralDescriptionIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV11GeneralDescriptionIdPut
     *
     * Updates the defined general description with the data provided as input..
     *
     */
    public function testApiV11GeneralDescriptionIdPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV11GeneralDescriptionListGet
     *
     * Fetches all the information related to requested statutory service general descriptions..
     *
     */
    public function testApiV11GeneralDescriptionListGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV11GeneralDescriptionNewGdListGet
     *
     * Gets the new statutory service general descriptions within PTV as a list of ids and names..
     *
     */
    public function testApiV11GeneralDescriptionNewGdListGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV11GeneralDescriptionPost
     *
     * Creates a new general description with the data provided as input..
     *
     */
    public function testApiV11GeneralDescriptionPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
