<?php
/**
 * OrganizationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Tampere\PtvV11
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PTV Open Api version 11
 *
 * Here you can see listed all the PTV Open Api methods.
 *
 * OpenAPI spec version: v11
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.29
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Tampere\PtvV11;

use Tampere\PtvV11\Configuration;
use Tampere\PtvV11\ApiException;
use Tampere\PtvV11\ObjectSerializer;

/**
 * OrganizationApiTest Class Doc Comment
 *
 * @category Class
 * @package  Tampere\PtvV11
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrganizationApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for apiV11OrganizationAreaAreaCodeCodeGet
     *
     * Gets a list of published organizations related to defined area and code.  Organizations created/modified after certain date can be fetched by adding date as query string parameter.  Organizations created/modified before certain date can be fetched by adding dateBefore as query string parameter..
     *
     */
    public function testApiV11OrganizationAreaAreaCodeCodeGet()
    {
    }

    /**
     * Test case for apiV11OrganizationBusinesscodeCodeGet
     *
     * Fetches all the information related to organizations with defined business identity code..
     *
     */
    public function testApiV11OrganizationBusinesscodeCodeGet()
    {
    }

    /**
     * Test case for apiV11OrganizationGet
     *
     * Gets all the published organizations within PTV as a list of organization ids and names.  Organizations created/modified after certain date can be fetched by adding date as query string parameter.  Organizations created/modified before certain date can be fetched by adding dateBefore as query string parameter.  Archived items can be fetched by setting status parameter as 'Archived' and withdrawn items can be fetched by setting status parameter as 'Withdrawn'..
     *
     */
    public function testApiV11OrganizationGet()
    {
    }

    /**
     * Test case for apiV11OrganizationHierarchyGet
     *
     * Gets a list of published organizations that do not have a parent organization.  Organizations created/modified after certain date can be fetched by adding date as query string parameter.  Organizations created/modified before certain date can be fetched by adding dateBefore as query string parameter..
     *
     */
    public function testApiV11OrganizationHierarchyGet()
    {
    }

    /**
     * Test case for apiV11OrganizationHierarchyIdGet
     *
     * Get a single organization hierarchy. Returns the complete hierarchy starting from  the root organization and including all the child and grandchild organizations..
     *
     */
    public function testApiV11OrganizationHierarchyIdGet()
    {
    }

    /**
     * Test case for apiV11OrganizationIdGet
     *
     * Fetches all the information related to a single organization..
     *
     */
    public function testApiV11OrganizationIdGet()
    {
    }

    /**
     * Test case for apiV11OrganizationIdPut
     *
     * Updates organization..
     *
     */
    public function testApiV11OrganizationIdPut()
    {
    }

    /**
     * Test case for apiV11OrganizationListAreaAreaCodeCodeGet
     *
     * Fetches all the information of the organizations related to certain area..
     *
     */
    public function testApiV11OrganizationListAreaAreaCodeCodeGet()
    {
    }

    /**
     * Test case for apiV11OrganizationListGet
     *
     * Fetches all the information related to requested organizations..
     *
     */
    public function testApiV11OrganizationListGet()
    {
    }

    /**
     * Test case for apiV11OrganizationOidOidGet
     *
     * Fetches all the information related to a single organization with defined Oid..
     *
     */
    public function testApiV11OrganizationOidOidGet()
    {
    }

    /**
     * Test case for apiV11OrganizationPost
     *
     * Creates a new organization with the data provided as input..
     *
     */
    public function testApiV11OrganizationPost()
    {
    }

    /**
     * Test case for apiV11OrganizationSahaGet
     *
     * Gets main organizations and two sub levels of organizations. Returns both published and archived organizations.  NOTE! This is a restricted endpoint..
     *
     */
    public function testApiV11OrganizationSahaGet()
    {
    }

    /**
     * Test case for apiV11OrganizationSahaIdGet
     *
     * Fetches Saha related information of a single organization.  NOTE! This is a restricted endpoint..
     *
     */
    public function testApiV11OrganizationSahaIdGet()
    {
    }

    /**
     * Test case for apiV11OrganizationSourceIdSourceIdPut
     *
     * Updates organization..
     *
     */
    public function testApiV11OrganizationSourceIdSourceIdPut()
    {
    }
}
